#!/usr/bin/env python3
"""
phash_baseline.py — In-sandbox pHash baseline retrieval over 12 silhouette SVGs.

Why this exists: the primary CLIP PoC (build_index.py + eval.py) requires
HuggingFace + Wikimedia, both blocked by the Claude Code sandbox firewall.
This script proves the retrieval *pipeline* (load → encode → index → query
→ eval) actually closes end-to-end with real numbers, using:

  - The 12 silhouette SVGs in assets/silhouettes/ (local, no network)
  - Pure-Python perceptual hash (no ML weights needed)
  - Leave-one-out form-family retrieval eval

pHash is NOT CLIP and the numbers reported here are NOT comparable to the
Phase 1 §6.3 targets (P@1 ≥ 0.40 / P@5 ≥ 0.60). pHash on silhouettes is a
shape-similarity proxy, useful as a **lower-bound baseline**: "if pHash gets
this number, CLIP must beat it to be worth deploying."

Run:
    pip install cairosvg imagehash pillow numpy
    python phash_baseline.py --silhouettes ../../assets/silhouettes --report phash-eval-report.md
"""
import argparse
import io
import json
from pathlib import Path

import cairosvg
import imagehash
from PIL import Image

# Form-family ground truth — hand-curated per silhouette inventory.
# Two-member families allow meaningful nearest-neighbor eval. Singletons
# have no intra-family match by construction (they score 0/0 — excluded).
FAMILY = {
    "fangding":          "ding",       # 方鼎 — square 鼎
    "yuanding":          "ding",       # 圆鼎 — round 鼎
    "fang_zun":          "zun",        # 方尊 — square 尊
    "xiao_zun":          "zun",        # 鸮尊 — owl 尊
    "sanxingdui_zongmu": "sanxingdui", # 三星堆 纵目面具
    "sanxingdui_dali_ren": "sanxingdui", # 三星堆 大立人
    "gui":               "gui",        # 簋
    "pan":               "pan",        # 盘
    "fanghu":            "hu",         # 方壶
    "bianzhong":         "bianzhong",  # 编钟
    "changxin_gongdeng": "deng",       # 长信宫灯
    "yuewang_jian":      "jian",       # 越王剑
}


def render_svg_to_image(svg_path: Path, size: int = 224) -> Image.Image:
    png_bytes = cairosvg.svg2png(
        url=str(svg_path), output_width=size, output_height=size,
        background_color="white",
    )
    return Image.open(io.BytesIO(png_bytes)).convert("RGB")


def evaluate_loo(items: list[dict], hashes: list[imagehash.ImageHash], top_k: int = 5) -> dict:
    """For each item, hold out, retrieve top-k by Hamming distance over rest.
    Score: did the top-1 retrieval share the same family?
    """
    n = len(items)
    intra_family_at_1 = 0
    intra_family_at_5 = 0
    failures = []
    per_item = []

    multi_member_families = {f for f in [it["family"] for it in items]
                              if [x["family"] for x in items].count(f) >= 2}

    for i, item in enumerate(items):
        rest_items = [items[j] for j in range(n) if j != i]
        rest_hashes = [hashes[j] for j in range(n) if j != i]
        distances = [(hashes[i] - h, k) for k, h in enumerate(rest_hashes)]
        distances.sort(key=lambda x: x[0])
        topk = [(rest_items[k], d) for d, k in distances[:top_k]]

        top1_item, top1_dist = topk[0]
        is_intra1 = top1_item["family"] == item["family"]
        is_intra5 = any(t[0]["family"] == item["family"] for t in topk)

        if item["family"] in multi_member_families:
            intra_family_at_1 += int(is_intra1)
            intra_family_at_5 += int(is_intra5)
            if not is_intra5:
                failures.append({"query": item["id"], "query_family": item["family"],
                                 "top1": top1_item["id"], "top1_family": top1_item["family"],
                                 "top1_dist": top1_dist})

        per_item.append({
            "id": item["id"], "family": item["family"],
            "top1_id": top1_item["id"], "top1_family": top1_item["family"],
            "top1_dist": int(top1_dist),
            "intra_family_at_1": is_intra1,
            "scored": item["family"] in multi_member_families,
        })

    n_scorable = sum(1 for it in items if it["family"] in multi_member_families)
    return {
        "n_total": n,
        "n_scorable": n_scorable,
        "n_excluded_singletons": n - n_scorable,
        "intra_family_p_at_1": intra_family_at_1 / n_scorable if n_scorable else 0,
        "intra_family_p_at_5": intra_family_at_5 / n_scorable if n_scorable else 0,
        "failures": failures,
        "per_item": per_item,
        "multi_member_families": sorted(multi_member_families),
    }


def write_report(report_path: Path, metrics: dict, items: list[dict]):
    families = {}
    for it in items:
        families.setdefault(it["family"], []).append(it["id"])

    lines = [
        "# pHash Baseline Eval Report (in-sandbox)",
        "",
        "> Auto-generated by `phash_baseline.py`. Real numbers from real silhouettes.",
        "> This is a **shape-similarity baseline**, not CLIP. See `IMPLEMENTATION-NOTES.md §5`",
        "> for why we ran this in-sandbox while the CLIP pipeline stays as the upgrade path.",
        "",
        "## Headline metrics",
        "",
        "| Metric | Value | Note |",
        "|---|---|---|",
        f"| Items total | {metrics['n_total']} | 12 silhouettes from `assets/silhouettes/` |",
        f"| Items scorable | {metrics['n_scorable']} | only multi-member families: {', '.join(metrics['multi_member_families'])} |",
        f"| Singletons excluded | {metrics['n_excluded_singletons']} | no possible intra-family match |",
        f"| Intra-family P@1 | **{metrics['intra_family_p_at_1']:.3f}** | top-1 nearest neighbor shares family |",
        f"| Intra-family P@5 | **{metrics['intra_family_p_at_5']:.3f}** | family member in top-5 |",
        "",
        "## Family inventory",
        "",
        "| Family | Members |",
        "|---|---|",
    ]
    for fam, ids in sorted(families.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        lines.append(f"| {fam} ({len(ids)}) | {', '.join(ids)} |")

    lines += [
        "",
        "## Per-item retrieval",
        "",
        "| Query | Family | Top-1 | Top-1 family | Distance | Family match? | Scored? |",
        "|---|---|---|---|---|---|---|",
    ]
    for it in metrics["per_item"]:
        ok = "✓" if it["intra_family_at_1"] else "✗"
        scored = "yes" if it["scored"] else "—"
        lines.append(f"| {it['id']} | {it['family']} | {it['top1_id']} | {it['top1_family']} | "
                     f"{it['top1_dist']} | {ok} | {scored} |")

    lines += [
        "",
        "## Interpretation",
        "",
        "**This is NOT a substitute for the CLIP eval.** pHash on silhouettes measures",
        "**shape pixel-overlap similarity**, not semantic visual similarity. A pHash baseline of",
        f"P@1={metrics['intra_family_p_at_1']:.2f} on 12 silhouettes tells us:",
        "",
        "1. The retrieval **pipeline closes end-to-end** in-sandbox (load → encode → index → query → eval)",
        "2. pHash on silhouettes is a **trivial baseline** — CLIP-grade semantic retrieval should",
        f"   meaningfully beat {metrics['intra_family_p_at_1']:.2f} on the same task",
        "3. The CLIP eval in `eval.py` is the proper Phase 1 §6.3 target; this baseline is just",
        "   the in-sandbox sanity proof that the engineering plumbing works",
        "",
        "## Why we ran this",
        "",
        "Per case-study §5.9, the sandbox firewall blocks HuggingFace and Wikimedia, making the",
        "CLIP+real-photo pipeline impossible to execute here. We had three options:",
        "",
        "1. Don't run anything, claim infrastructure constraint, ship CLIP code only (the original Plan A)",
        "2. Fake numbers (immediately disqualifying — see §5.9)",
        "3. **Run a degenerate-but-real baseline on what IS available locally** — this report",
        "",
        "Option 3 was the user's explicit request: 'try multiple ways before falling back to Plan A.'",
        "This file is option 3. CLIP `eval-report.md` template still awaits off-sandbox execution.",
    ]
    report_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--silhouettes", type=Path, default=Path("../../assets/silhouettes"))
    ap.add_argument("--report", type=Path, default=Path("phash-eval-report.md"))
    ap.add_argument("--size", type=int, default=224, help="raster size for pHash")
    ap.add_argument("--top-k", type=int, default=5)
    args = ap.parse_args()

    items = []
    hashes = []
    for svg in sorted(args.silhouettes.glob("*.svg")):
        stem = svg.stem
        if stem not in FAMILY:
            print(f"  [skip-unknown-family] {stem}")
            continue
        img = render_svg_to_image(svg, args.size)
        h = imagehash.phash(img)
        items.append({"id": stem, "family": FAMILY[stem], "svg_path": str(svg)})
        hashes.append(h)
        print(f"  [encoded] {stem} (family={FAMILY[stem]}) phash={h}")

    print(f"\nEvaluating {len(items)} items, leave-one-out top-{args.top_k}…")
    metrics = evaluate_loo(items, hashes, top_k=args.top_k)
    print(f"  intra-family P@1 = {metrics['intra_family_p_at_1']:.3f}")
    print(f"  intra-family P@5 = {metrics['intra_family_p_at_5']:.3f}")
    print(f"  n_scorable = {metrics['n_scorable']}/{metrics['n_total']}")

    write_report(args.report, metrics, items)
    print(f"\nReport → {args.report}")


if __name__ == "__main__":
    main()
